name: test

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-lateset
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - run: npm run lint
        name: Lint code
